apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deploy
  namespace: nodejs-app
  labels:
    app: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: rehab16/nodejs-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_DATABASE
              value: "taskdb"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
            - name: DB_PORT
              value: "5432"
          # resources:
          #   requests:
          #     memory: "256Mi"
          #   limits:
          #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: nodejs-app
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - name: nodejs-app
      port: 3000
      targetPort: 3000

